### ISSUE TITLE
cannot import variables

### ISSUE THREAD

**Issue by p-view** [buepro/typo3-user_pizpalue#3]
I want to change $primary and $secondary color. I testet in presets and variables scss files (pp-enable-user-presets = true).
No effect. Also change color by constants fail.

when i do includeCSS.theme = EXT:user_pizpalue/Resources/Public/Scss/theme.scss (not includeCSS.upGeneralScss) with this code:
@import "variables";
@import "../../../../pizpalue/Resources/Public/Scss/Bootstrap5/theme-main";

all fine

BR Micha

typo310
bootstrap_package | 12.1.0-dev
pizpalue | 12.0.0-dev

**Comment by buepro** [comment]
Could you check if the static template (Customization (user_pizpalue)) has been added to the root template?
